### ISSUE TITLE
Expecting a readme for flowercount 

### ISSUE THREAD

**Issue by simi-hub** [simi-hub/friendly-giggle#5]
A read me file is expected for the flower count program

**Comment by myselfdeepdas** [comment]
HOW CAN I HELP YOU TO THIS PROJECT ? I WANT TO CONTRIBUTE IN IT , PLEASE ASSIST ME.

**Comment by simi-hub** [comment]
> HOW CAN I HELP YOU TO THIS PROJECT ? I WANT TO CONTRIBUTE IN IT , PLEASE ASSIST ME.

Hello, I am not doing anything serious with it. Like the read me file said..I am just answering a bunch of question so I can understand how github works.  I also intentionally opened the issue so I can close it later. I do appreciate the help, but I think I am okay

**Comment by simi-hub** [comment]
Readme file for FlowerCounter has been added
